//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_loja.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/Loja_Web_services.Entidade.Entidade")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscal", Namespace="http://schemas.datacontract.org/2004/07/Loja_Web_services.Entidade.Entidade")]
    [System.SerializableAttribute()]
    public partial class NotaFiscal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projeto_loja.ServiceReference1.Produto[] ProdutosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ValorTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNota {
            get {
                return this.DataNotaField;
            }
            set {
                if ((this.DataNotaField.Equals(value) != true)) {
                    this.DataNotaField = value;
                    this.RaisePropertyChanged("DataNota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projeto_loja.ServiceReference1.Produto[] Produtos {
            get {
                return this.ProdutosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutosField, value) != true)) {
                    this.ProdutosField = value;
                    this.RaisePropertyChanged("Produtos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ValorTotal {
            get {
                return this.ValorTotalField;
            }
            set {
                if ((this.ValorTotalField.Equals(value) != true)) {
                    this.ValorTotalField = value;
                    this.RaisePropertyChanged("ValorTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveProduto", ReplyAction="http://tempuri.org/IService1/SaveProdutoResponse")]
        bool SaveProduto(Projeto_loja.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveProduto", ReplyAction="http://tempuri.org/IService1/SaveProdutoResponse")]
        System.Threading.Tasks.Task<bool> SaveProdutoAsync(Projeto_loja.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduto", ReplyAction="http://tempuri.org/IService1/UpdateProdutoResponse")]
        bool UpdateProduto(Projeto_loja.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduto", ReplyAction="http://tempuri.org/IService1/UpdateProdutoResponse")]
        System.Threading.Tasks.Task<bool> UpdateProdutoAsync(Projeto_loja.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveNota", ReplyAction="http://tempuri.org/IService1/SaveNotaResponse")]
        bool SaveNota(Projeto_loja.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveNota", ReplyAction="http://tempuri.org/IService1/SaveNotaResponse")]
        System.Threading.Tasks.Task<bool> SaveNotaAsync(Projeto_loja.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNota", ReplyAction="http://tempuri.org/IService1/UpdateNotaResponse")]
        bool UpdateNota(Projeto_loja.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNota", ReplyAction="http://tempuri.org/IService1/UpdateNotaResponse")]
        System.Threading.Tasks.Task<bool> UpdateNotaAsync(Projeto_loja.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduto", ReplyAction="http://tempuri.org/IService1/DeleteProdutoResponse")]
        bool DeleteProduto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduto", ReplyAction="http://tempuri.org/IService1/DeleteProdutoResponse")]
        System.Threading.Tasks.Task<bool> DeleteProdutoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProdutos", ReplyAction="http://tempuri.org/IService1/GetProdutosResponse")]
        Projeto_loja.ServiceReference1.Produto[] GetProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProdutos", ReplyAction="http://tempuri.org/IService1/GetProdutosResponse")]
        System.Threading.Tasks.Task<Projeto_loja.ServiceReference1.Produto[]> GetProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNotas", ReplyAction="http://tempuri.org/IService1/GetNotasResponse")]
        Projeto_loja.ServiceReference1.NotaFiscal[] GetNotas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNotas", ReplyAction="http://tempuri.org/IService1/GetNotasResponse")]
        System.Threading.Tasks.Task<Projeto_loja.ServiceReference1.NotaFiscal[]> GetNotasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Projeto_loja.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Projeto_loja.ServiceReference1.IService1>, Projeto_loja.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveProduto(Projeto_loja.ServiceReference1.Produto p) {
            return base.Channel.SaveProduto(p);
        }
        
        public System.Threading.Tasks.Task<bool> SaveProdutoAsync(Projeto_loja.ServiceReference1.Produto p) {
            return base.Channel.SaveProdutoAsync(p);
        }
        
        public bool UpdateProduto(Projeto_loja.ServiceReference1.Produto p) {
            return base.Channel.UpdateProduto(p);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProdutoAsync(Projeto_loja.ServiceReference1.Produto p) {
            return base.Channel.UpdateProdutoAsync(p);
        }
        
        public bool SaveNota(Projeto_loja.ServiceReference1.Produto p) {
            return base.Channel.SaveNota(p);
        }
        
        public System.Threading.Tasks.Task<bool> SaveNotaAsync(Projeto_loja.ServiceReference1.Produto p) {
            return base.Channel.SaveNotaAsync(p);
        }
        
        public bool UpdateNota(Projeto_loja.ServiceReference1.Produto p) {
            return base.Channel.UpdateNota(p);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateNotaAsync(Projeto_loja.ServiceReference1.Produto p) {
            return base.Channel.UpdateNotaAsync(p);
        }
        
        public bool DeleteProduto(int id) {
            return base.Channel.DeleteProduto(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProdutoAsync(int id) {
            return base.Channel.DeleteProdutoAsync(id);
        }
        
        public Projeto_loja.ServiceReference1.Produto[] GetProdutos() {
            return base.Channel.GetProdutos();
        }
        
        public System.Threading.Tasks.Task<Projeto_loja.ServiceReference1.Produto[]> GetProdutosAsync() {
            return base.Channel.GetProdutosAsync();
        }
        
        public Projeto_loja.ServiceReference1.NotaFiscal[] GetNotas() {
            return base.Channel.GetNotas();
        }
        
        public System.Threading.Tasks.Task<Projeto_loja.ServiceReference1.NotaFiscal[]> GetNotasAsync() {
            return base.Channel.GetNotasAsync();
        }
    }
}
